# 1.1-1.2: Systems of Linear Equations, Row Reduction, Echelon Forms

In [1]:
import numpy as np

### 1.1 #25

In [3]:
# Find an equation involving g, h, and k that makes this a consistent system

A = np.array([[1, -4, 7],[0, 3, -5,],[-2, 5, -9]]) # g, h, k

In [4]:
A

array([[ 1, -4,  7],
       [ 0,  3, -5],
       [-2,  5, -9]])

In [9]:
A[2] = A[2] + A[0] * 2

In [10]:
A

array([[ 1, -4,  7],
       [ 0,  3, -5],
       [ 0, -3,  5]])

In [13]:
A[2] = A[1] + A[2]

In [15]:
A  # k + 2g + h

array([[ 1, -4,  7],
       [ 0,  3, -5],
       [ 0,  0,  0]])

In [18]:
# So, k + 2g + h = 0
# Consistent when k + 2g + h = 0
# Given those conditions, x3 is free

## 1.2 #21

In [22]:
%reset

In [23]:
# Qa: In some cases, a matrix may be row reduced to more than one matrix in reduced echelon form, using different sequences of row operations

# A: False. By definition, the reduced echelon form of a matrix is unique.
# But, there are different versions of normal echelon form.

In [24]:
# Qc: A basic variable in a linear system is a variable that corresponds to a pivot column in the coefficient matrix.

# A: Basic variables are non-free variables.

In [25]:
# Qd: Finding a parametric description of the solution set of a linear system is the same as solving the system.

# A: True. Parametric descriptions just involve solving in terms of variables rather than numbers.

In [26]:
# Qe. If one row in an echelon form of an augmented matrix is [0 0 0 5 0], then the associated linear system is inconsistent.

# A: False. It could still be inconsistent, but this wouldn't be why.

## 1.2 Exercises

3

In [1]:
import numpy as np

In [35]:
A = np.matrix('1 2 3 4; 4 5 6 7; 6 7 8 9')
A

matrix([[1, 2, 3, 4],
        [4, 5, 6, 7],
        [6, 7, 8, 9]])

In [18]:
A[1] = A[1] - (4 * A[0])

In [19]:
A

matrix([[ 1,  2,  3,  4],
        [ 0, -3, -6, -9],
        [ 6,  7,  8,  9]])

In [20]:
A[2] = A[2] - (6 * A[0])

In [21]:
A

matrix([[  1,   2,   3,   4],
        [  0,  -3,  -6,  -9],
        [  0,  -5, -10, -15]])

In [25]:
A[2] = A[2] - ((5/3) * A[1])

In [26]:
A

matrix([[ 1,  2,  3,  4],
        [ 0, -3, -6, -9],
        [ 0,  0,  0,  0]])

In [31]:
A[1] = A[1] / -3

In [33]:
A[0] = A[0] - (2 * A[1])

In [34]:
A

matrix([[ 1,  0, -1, -2],
        [ 0,  1,  2,  3],
        [ 0,  0,  0,  0]])

4

In [41]:
%reset

In [42]:
import numpy as np

In [43]:
A = np.matrix('1 3 5 7; 3 5 7 9; 5 7 9 1')
A

matrix([[1, 3, 5, 7],
        [3, 5, 7, 9],
        [5, 7, 9, 1]])

9

In [44]:
A = np.matrix('0 1 -6 5; 1 -2 7 -6')
A

matrix([[ 0,  1, -6,  5],
        [ 1, -2,  7, -6]])

In [45]:
A[1] = A[1] + (2 * A[0])

In [50]:
A = A[[1, 0]]

In [51]:
A

matrix([[ 1,  0, -5,  4],
        [ 0,  1, -6,  5]])

10

In [54]:
A = np.matrix('1 -2 -1 3; 3 -6 -2 2')

In [55]:
A

matrix([[ 1, -2, -1,  3],
        [ 3, -6, -2,  2]])

In [56]:
A[1] = A[1] - (3 * A[0])

In [57]:
A

matrix([[ 1, -2, -1,  3],
        [ 0,  0,  1, -7]])

In [59]:
A[0] = A[0] + A[1]; A

matrix([[ 1, -2,  0, -4],
        [ 0,  0,  1, -7]])

11

In [60]:
A = np.matrix('3 -4 2 0; -9 12 -6 0; -6 8 -4 0')

In [61]:
A

matrix([[ 3, -4,  2,  0],
        [-9, 12, -6,  0],
        [-6,  8, -4,  0]])

In [62]:
A[1] = A[1] + (3 * A[0])
A[2] = A[2] + (2 * A[0])
A

matrix([[ 3, -4,  2,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]])