# 1.1-1.2: Systems of Linear Equations, Row Reduction, Echelon Forms

In [1]:
import numpy as np

### 1.1 #25

In [3]:
# Find an equation involving g, h, and k that makes this a consistent system

A = np.array([[1, -4, 7],[0, 3, -5,],[-2, 5, -9]]) # g, h, k

In [4]:
A

array([[ 1, -4,  7],
       [ 0,  3, -5],
       [-2,  5, -9]])

In [9]:
A[2] = A[2] + A[0] * 2

In [10]:
A

array([[ 1, -4,  7],
       [ 0,  3, -5],
       [ 0, -3,  5]])

In [13]:
A[2] = A[1] + A[2]

In [15]:
A  # k + 2g + h

array([[ 1, -4,  7],
       [ 0,  3, -5],
       [ 0,  0,  0]])

In [18]:
# So, k + 2g + h = 0
# Consistent when k + 2g + h = 0
# Given those conditions, x3 is free

## 1.2 #21

In [22]:
%reset

In [23]:
# Qa: In some cases, a matrix may be row reduced to more than one matrix in reduced echelon form, using different sequences of row operations

# A: False. By definition, the reduced echelon form of a matrix is unique.
# But, there are different versions of normal echelon form.

In [24]:
# Qc: A basic variable in a linear system is a variable that corresponds to a pivot column in the coefficient matrix.

# A: Basic variables are non-free variables.

In [25]:
# Qd: Finding a parametric description of the solution set of a linear system is the same as solving the system.

# A: True. Parametric descriptions just involve solving in terms of variables rather than numbers.

In [26]:
# Qe. If one row in an echelon form of an augmented matrix is [0 0 0 5 0], then the associated linear system is inconsistent.

# A: False. It could still be inconsistent, but this wouldn't be why.

## Section 1.3: Vector Equations

In [35]:
%reset
import numpy as np