# 1.3 - 1.4: Vector Equations, The Matrix Equation

In [1]:
import numpy as np

## 1.3

To find h, solve this system of linear equations:

\begin{bmatrix}
    1 & 5 & -3 & -4\\
    -1 & -4 & 1 & 3\\
    -2 & -7 & 0 & h
\end{bmatrix}


## 1.4 The Equation $A\vec x = \vec b$

In [3]:
A = np.array([[2, 3, 4, 7], [1, 6, 0, -3]]) ; A  # matrix

array([[ 2,  3,  4,  7],
       [ 1,  6,  0, -3]])

In [4]:
X = np.array([-1, 5, 0, 11]); X  # vector

array([-1,  5,  0, 11])

In [7]:
A * X # Multiplying them together

array([[ -2,  15,   0,  77],
       [ -1,  30,   0, -33]])

In [8]:
(A * X).sum(axis=1) # Get the resulting vector

array([90, -4])

In [21]:
%reset

In [1]:
import numpy as np
import scipy as sp

In [23]:
b = np.array([.45, .25, .15])  # Cost of materials, labor, overhead for prod. a
c = np.array([.40, .30, .15])  # Cost of materials, labor, overhead for prod. b

In [24]:
b

array([ 0.45,  0.25,  0.15])

In [25]:
c

array([ 0.4 ,  0.3 ,  0.15])

In [34]:
A = np.array([b, c]).T

In [35]:
A

array([[ 0.45,  0.4 ],
       [ 0.25,  0.3 ],
       [ 0.15,  0.15]])

In [37]:
A[:, 0] * 100  # Cost of $100 worth of bm

array([ 45.,  25.,  15.])

### 4 / 12 / 2018: finishing up 1.4