# 1.5: Solution Sets of Linear Equations

1,4,6,7,8,9,10,13,14,15,16,18,23,24,26,28

In [41]:
import pandas as pd
import numpy as np
from scipy import linalg

## Practice Problems

### 1

In [84]:
A = np.mat('1 4 -5; 2 -1 8')

In [85]:
b = np.mat('0 9')

In [88]:
A * A.I

matrix([[  1.00000000e+00,  -1.11022302e-16],
        [ -2.22044605e-16,   1.00000000e+00]])

## Exercises

### 1

In [103]:
# np.matrix: matrix class with a better interface than ndarray for matrix operations.
# Determine if there is a nontrivial solution
A = np.matrix('2 -5 8 0; -2 -7 1 0; 4 2 7 0')
b = np.matrix('0 0 0')

In [105]:
A

matrix([[ 2, -5,  8,  0],
        [-2, -7,  1,  0],
        [ 4,  2,  7,  0]])

In [106]:
b

matrix([[0, 0, 0]])

In [107]:
A[1] = A[1] + A[0]

In [108]:
A

matrix([[  2,  -5,   8,   0],
        [  0, -12,   9,   0],
        [  4,   2,   7,   0]])

In [109]:
A[2] = A[2] - (2 * A[0])

In [110]:
A

matrix([[  2,  -5,   8,   0],
        [  0, -12,   9,   0],
        [  0,  12,  -9,   0]])

In [111]:
A[2] = A[2] + A[1]

In [113]:
A # So this system has a nontrivial solution (e.g. one variable is free).

matrix([[  2,  -5,   8,   0],
        [  0, -12,   9,   0],
        [  0,   0,   0,   0]])

### 2

In [124]:
A = np.matrix('1 -3 7 0; -2 1 -4 0; 1 2 9 0')

In [125]:
A

matrix([[ 1, -3,  7,  0],
        [-2,  1, -4,  0],
        [ 1,  2,  9,  0]])

In [126]:
A[1] = A[1] + (2 * A[0])

In [127]:
A

matrix([[ 1, -3,  7,  0],
        [ 0, -5, 10,  0],
        [ 1,  2,  9,  0]])

In [128]:
A[2] = A[2] - A[0]

In [129]:
A

matrix([[ 1, -3,  7,  0],
        [ 0, -5, 10,  0],
        [ 0,  5,  2,  0]])

In [130]:
A[2] = A[2] + A[1]

In [131]:
A

matrix([[ 1, -3,  7,  0],
        [ 0, -5, 10,  0],
        [ 0,  0, 12,  0]])

In [132]:
# Only a trivial solution