# 1.6 Applications of Linear Systems

In [33]:
import numpy as np
import pandas as pd

# Example 1: Model Economy

In [32]:
A = np.matrix('.0 .4 .6; .6 .1 .2; .4 .5 .2')
A

matrix([[ 0. ,  0.4,  0.6],
        [ 0.6,  0.1,  0.2],
        [ 0.4,  0.5,  0.2]])

The rows represent who the output was purchased by.

The columns represent fractional parts of a sector's total output.

So, a sector looks down a column to see where its output goes, and it looks across a row to see what it needs as inputs.

In [34]:
df = pd.DataFrame(A, columns=['Coal', 'Electric', 'Steel'], index=['Coal', 'Electric', 'Steel'])
df

Coal  Electric  Steel
Coal       0.0       0.4    0.6
Electric   0.6       0.1    0.2
Steel      0.4       0.5    0.2

## TODO

Find equilibrium prices that make each sector's income match its expenditures.
Answer ends up being:

Coal priced \$94 million

Electric priced \$85 million

Steel priced \$100 million

# 1.7: Linear Independence

In [5]:
import numpy as np
import pandas as pd

In [15]:
A = np.matrix('0 1 2; 3 4 5; 6 7 8')
A

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [8]:
pd.DataFrame(A, columns=['A', 'B', 'C'])

A  B  C
0  0  1  2
1  3  4  5
2  6  7  8

array([0, 1, 2])

In [26]:
np.matrix([0, 1, 2]).T

matrix([[0],
        [1],
        [2]])

In [28]:
A

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [29]:
np.matrix([0, 1, 2]).T

matrix([[0],
        [1],
        [2]])

In [31]:
A * np.matrix([0, 1, 2]).T

matrix([[ 5],
        [14],
        [23]])