# Matrix operations

In [2]:
import numpy as np
import sympy as sp

In [17]:
B = np.matrix('0 -1; 1 0')
P = np.matrix('1 1; 0 1')
Pi = np.linalg.inv(P)

In [20]:
A = P * B * Pi
A

matrix([[ 1., -2.],
        [ 1., -1.]])

In [24]:
Pi * A * P

matrix([[ 0., -1.],
        [ 1.,  0.]])

In [25]:
A * P

matrix([[ 1., -1.],
        [ 1.,  0.]])