# 3.1 Intro to Determinants

In [1]:
import numpy as np
import sympy as sp
from numpy.linalg import det

## Computing determinant

### Cofactor expansion across row 1

In [2]:
A = np.matrix('1 5 0; 2 4 -1; 0 -2 0')
A

matrix([[ 1,  5,  0],
        [ 2,  4, -1],
        [ 0, -2,  0]])

In [15]:
int(det(A).round())  # determinant we're looking for

-2

In [18]:
1 * det(np.matrix('4 -1; -2 0')) - 5 * det(np.matrix('2 -1; 0 0'))  # Determinant formula works

-2.0

### Cofactor expansion across any row

In [19]:
A  # Row 3

matrix([[ 1,  5,  0],
        [ 2,  4, -1],
        [ 0, -2,  0]])

In [21]:
2 * det(np.matrix('1 0; 2 -1'))

-2.0

In [22]:
A  # Column 3

matrix([[ 1,  5,  0],
        [ 2,  4, -1],
        [ 0, -2,  0]])

In [25]:
det(np.matrix('1 5; 0 -2'))

-2.0

In [27]:
A = np.matrix('3 -7 8 9 -6; 0 2 -5 7 3; 0 0 1 5 0; 0 0 2 4 -1; 0 0 0 -2 0')
A  # Computing determinants of a bigger matrix

matrix([[ 3, -7,  8,  9, -6],
        [ 0,  2, -5,  7,  3],
        [ 0,  0,  1,  5,  0],
        [ 0,  0,  2,  4, -1],
        [ 0,  0,  0, -2,  0]])

In [13]:
import numpy as np
from numpy.linalg import det

In [16]:
A = np.matrix('2 0 0 8; 1 -7 -5 0; 3 8 6 0; 0 7 5 4')

0

In [8]:
np.round(np.linalg.det(A))

0.0