In [8]:
import numpy as np
import sympy as sp
from numpy.linalg import det, solve
from sympy import Matrix

In [5]:
A = np.matrix('3 -5 -3; 6 -2 0; -8 4 1')

In [16]:
A

matrix([[ 3, -5, -3],
        [ 6, -2,  0],
        [-8,  4,  1]])

In [20]:
A * np.matrix('1 3 -4').T

matrix([[0],
        [0],
        [0]])

In [2]:
import numpy as np

In [4]:
np.matrix('1 -2; -3 4')

matrix([[ 1, -2],
        [-3,  4]])

In [5]:
np.matrix('5 6').T

matrix([[5],
        [6]])

In [3]:
np.matrix('1 -2; -3 4') * np.matrix('5 6').T

matrix([[-7],
        [ 9]])