In [1]:
import numpy as np

# Become mega-pro at array operations

In [127]:
a = np.array([range(i, i+4) for i in [2, 4, 6, 8]])
a

array([[ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11]])

In [128]:
b = np.array([np.arange(i, i+4) for i in [10, 12, 14, 16]])
b

array([[10, 11, 12, 13],
       [12, 13, 14, 15],
       [14, 15, 16, 17],
       [16, 17, 18, 19]])

In [117]:
a[::-1, ::-1]

array([[11, 10,  9,  8],
       [ 9,  8,  7,  6],
       [ 7,  6,  5,  4],
       [ 5,  4,  3,  2]])

In [118]:
a.flatten()[::-1].reshape(4,4)

array([[11, 10,  9,  8],
       [ 9,  8,  7,  6],
       [ 7,  6,  5,  4],
       [ 5,  4,  3,  2]])

In [125]:
a.flatten()[:, np.newaxis]

array([[ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [ 8],
       [ 9],
       [10],
       [11]])

In [140]:
np.concatenate([a, b], axis=0)

array([[ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13],
       [12, 13, 14, 15],
       [14, 15, 16, 17],
       [16, 17, 18, 19]])

## Linear algebra

In [5]:
import numpy as np

In [33]:
A = np.array([[0, -1], [1, 0]])
B = np.array([-4, -1])

print(A, '\n\n', B)

[[ 0 -1]
 [ 1  0]] 

 [-4 -1]


In [35]:
Ai = (np.linalg.inv(A))

In [38]:
np.matmul(Ai, B)

array([-1.,  4.])

In [39]:
np.linalg.solve(A, B)

array([-1.,  4.])