# Statistics Problems: Ch 2

## Problems 1, 2, 4, 6, 7, 9, 10, 11, 14, 15

In [108]:
#  Import the golden standards
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

#### 1. A political incumbent commissions a survey on how well she is doing in office. Each participant in the survey rates the incumbent on a scale from 1 to 5, where 1 signifies "amominable" and 5 signifies "fantastic". The results of the 77 respondents produce the following ratings.

In [149]:
df = np.array([2,3,1,3,3,5,2,3,3,
              3,3,2,3,3,3,3,3,2,
              1,2,2,3,2,3,3,3,3,
              3,3,3,3,3,2,4,2,3,
              3,2,3,4,3,2,4,3,3,
              3,3,2,1,3,2,1,3,1,
              2,2,3,2,3,4,3,3,2])
df

array([2, 3, 1, 3, 3, 5, 2, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 2, 1, 2, 2, 3, 2,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 4, 2, 3, 3, 2, 3, 4, 3, 2, 4, 3, 3, 3,
       3, 2, 1, 3, 2, 1, 3, 1, 2, 2, 3, 2, 3, 4, 3, 3, 2])

#### a. Represent these numbers as a frequency distribution.

In [150]:
unique, counts = np.unique(df, return_counts=True)
f = dict(zip(unique, counts))  # Frequency distribution
dff = pd.Series(f)
dff

1     5
2    17
3    36
4     4
5     1
dtype: int64

#### b. Represent these numbers as a probability distribution.

In [154]:
dfp = dff / dff.sum()
dfp

1    0.079365
2    0.269841
3    0.571429
4    0.063492
5    0.015873
dtype: float64

In [165]:
dffp = pd.DataFrame([dff, dfp])
dffp = dffp.transpose()
dffp.columns = ['f(V)', 'p(V)']
dffp
dffp.sum()

f(V)      p(V)
1   5.0  0.079365
2  17.0  0.269841
3  36.0  0.571429
4   4.0  0.063492
5   1.0  0.015873

f(V)    63.0
p(V)     1.0
dtype: float64

#### 2

In [148]:
#meh

# A Break for Playing with Coin Tosses

### Using actual coins and np arrays

In [218]:
a = np.ones(22, dtype=int) # 0=tails, 1=heads. Flip 22 times and see heads.
a = np.append(a, np.zeros(8, dtype=int))
np.random.shuffle(a)

b = np.array([0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
               1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0])  # My actual flips

np.size(a[a<1])  # a is tails
np.size(a[b<1])  # b is tails
a
b

8

16

array([0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1])

array([0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0])

### Alternative way of simulating a coin situation

In [288]:
def coins():
    m = 0
    x = 100000
    for i in range(x):
        trials = np.random.randint(2, size=30)
        if (trials.sum() >= 22):
            m += 1
    return (m / x) * 100

p = coins()
p

0.8290000000000001

### Simulate by bootstrap resampling: draw samples from data's own distribution

In [309]:
data = np.array([48, 24, 51, 12, 21, 41, 25, 23, 32, 61, 19, 24, 29, 21, 23, 13, 32, 18, 42, 18], dtype=int)
xbar = []

for i in range(10000):
    sample = data[np.random.randint(20, size=20)]  # Draw 20 samples from data, with overlap
    xbar.append(np.mean(sample))

np.mean(xbar), np.std(xbar)

(28.883299999999998, 2.9245531470636674)

In [303]:
xbar = np.array([])
xbar

array([], dtype=float64)