In [1]:
import numpy as np

# Become mega-pro at array operations

In [127]:
a = np.array([range(i, i+4) for i in [2, 4, 6, 8]])
a

array([[ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11]])

In [128]:
b = np.array([np.arange(i, i+4) for i in [10, 12, 14, 16]])
b

array([[10, 11, 12, 13],
       [12, 13, 14, 15],
       [14, 15, 16, 17],
       [16, 17, 18, 19]])

In [117]:
a[::-1, ::-1]

array([[11, 10,  9,  8],
       [ 9,  8,  7,  6],
       [ 7,  6,  5,  4],
       [ 5,  4,  3,  2]])

In [118]:
a.flatten()[::-1].reshape(4,4)

array([[11, 10,  9,  8],
       [ 9,  8,  7,  6],
       [ 7,  6,  5,  4],
       [ 5,  4,  3,  2]])

In [125]:
a.flatten()[:, np.newaxis]

array([[ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [ 8],
       [ 9],
       [10],
       [11]])

In [140]:
np.concatenate([a, b], axis=0)

array([[ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13],
       [12, 13, 14, 15],
       [14, 15, 16, 17],
       [16, 17, 18, 19]])

## Linear algebra

In [1]:
import numpy as np

In [33]:
A = np.array([[0, -1], [1, 0]])
B = np.array([-4, -1])

print(A, '\n\n', B)

[[ 0 -1]
 [ 1  0]] 

 [-4 -1]


In [35]:
Ai = (np.linalg.inv(A))

In [38]:
np.matmul(Ai, B)

array([-1.,  4.])

In [39]:
np.linalg.solve(A, B)

array([-1.,  4.])

### Linear Algebra: Learning row-echelon form

In [123]:
A = np.array([[0, 3, -6, 6, 4, -5], [3, -7, 8, -5, 8, 9], [3, -9, 12, -9, 6, 15]])

In [124]:
A

array([[ 0,  3, -6,  6,  4, -5],
       [ 3, -7,  8, -5,  8,  9],
       [ 3, -9, 12, -9,  6, 15]])

In [125]:
A[[0, 2]] = A[[2, 0]]

In [126]:
A

array([[ 3, -9, 12, -9,  6, 15],
       [ 3, -7,  8, -5,  8,  9],
       [ 0,  3, -6,  6,  4, -5]])

In [127]:
A[1] = A[1] - A[0]

In [128]:
A

array([[ 3, -9, 12, -9,  6, 15],
       [ 0,  2, -4,  4,  2, -6],
       [ 0,  3, -6,  6,  4, -5]])

In [129]:
# Row Echelon Form
A[2] = A[2] - (A[1] * 3 / 2)

In [130]:
A

array([[ 3, -9, 12, -9,  6, 15],
       [ 0,  2, -4,  4,  2, -6],
       [ 0,  0,  0,  0,  1,  4]])

In [131]:
A[1] = A[1] - A[2] * 2

In [134]:
A

array([[  3,  -9,  12,  -9,   6,  15],
       [  0,   2,  -4,   4,   0, -14],
       [  0,   0,   0,   0,   1,   4]])

In [136]:
A[0] = A[0] - A[2] * 6

In [137]:
A

array([[  3,  -9,  12,  -9,   0,  -9],
       [  0,   2,  -4,   4,   0, -14],
       [  0,   0,   0,   0,   1,   4]])

In [141]:
A[0] = A[0] + A[1] / 2 * 9

In [142]:
A

array([[  3,   0,  -6,   9,   0, -72],
       [  0,   2,  -4,   4,   0, -14],
       [  0,   0,   0,   0,   1,   4]])

In [144]:
A[0] = A[0] / 3

In [146]:
A  # Reduced row-echelon form

array([[  1,   0,  -2,   3,   0, -24],
       [  0,   2,  -4,   4,   0, -14],
       [  0,   0,   0,   0,   1,   4]])

## Practicing from memory

In [1]:
import numpy as np

In [2]:
A = np.eye(3, 3)
A

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [3]:
np.vstack((A, np.array([0, 0, 0])))

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  0.]])

In [10]:
np.linspace(1, 10, 10)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [11]:
a = A

In [24]:
a

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [32]:
a = np.vstack((A, np.array([1, 1, 1])))

In [33]:
a

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  1.,  1.]])

In [48]:
b = np.array([2, 2, 2])

In [59]:
a = a.astype(int)

In [62]:
a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 1, 1]])

In [63]:
b

array([2, 2, 2])

In [80]:
b[np.newaxis].T

array([[2],
       [2],
       [2]])

In [95]:
a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 1, 1]])

In [98]:
c = np.hstack([a[0:3], b[np.newaxis].T])

In [99]:
c

array([[1, 0, 0, 2],
       [0, 1, 0, 2],
       [0, 0, 1, 2]])

In [123]:
np.hsplit(c, [1, 4])

[array([[1],
        [0],
        [0]]), array([[0, 0, 2],
        [1, 0, 2],
        [0, 1, 2]]), array([], shape=(3, 0), dtype=int32)]

In [172]:
np.random.seed(0)

In [173]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

In [180]:
values = np.random.randint(0, 11, size=10)
values

array([ 6,  8,  8, 10,  1,  6,  7,  7,  8,  1])

In [189]:
np.pi / 2

1.5707963267948966

In [206]:
x = np.arange(1, 6)
x

array([1, 2, 3, 4, 5])

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.]])